---
# tasks file for run_php_fpm_role
- name: install php-fpm
  apt:
    name: php-fpm
    state: latest

- name: start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: copying php_conf to remote_host
  copy:
    src: /etc/ansible/playbooks/file/www.conf
    dest: /etc/php/8.1/fpm/pool.d/www.conf
    remote_src: yes

- name: Set configuration file
  template:
    src: www.conf.j2
    dest: /etc/php/8.1/fpm/pool.d/www.conf
  notify: restart php-fpm
  tags: php-fpm
...
