---
# handlers file for run_nginx_role
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
