---
# tasks file for add_user_role
- name: Add 'user2' add grope 'superusers'.
  user:
      name: user2
      password: #зашифрованный пароль ansible-vault
      shell: /bin/bash
      groups: superusers
      append: yes

- name: Add 2048-bit SSH key
  user:
      name: user2
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

- name: Add authorized key in file id_rsa.pub
  authorized_key:
      user: user2
      state: present
      key: "{{ lookup('file', '/home/user2/.ssh/id_rsa.pub') }}"
...
