---
# tasks file for vsftpd
- name: install vsftpd
  apt:
    name: "{{ vsftpd_apt }}"
    state: latest

- name: start service vsftpd
  service:
        name: "{{ vsftpd_service }}"
        state: started
        enabled: yes

- name: Install configuration file
  template:
    src:   etc_vsftpd_vsftpd.conf.j2
    dest: "{{ vsftpd_config_file }}"
    mode: '0600'
  notify: restart vsftpd
